# Generated by Django 4.2.6 on 2023-11-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='path',
            field=models.CharField(default='/controlled_programs/basic_gui.py', max_length=200),
        ),
    ]
